### ISSUE TITLE
Error when Testing pretrained model

### ISSUE THREAD

**Issue by zhujiagang** [facebookresearch/DetectAndTrack#12] opened 2018-06-27 07:24 UTC
When I follow the command of Testing pre-trained models
```
$ python launch.py \
	--cfg configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml \
	--mode test \
	TEST.WEIGHTS pretrained_models/configs/video/2d_best/01_R101_best_hungarian.yaml/model_final.pkl
```
Error occurs
```
Done (t=0.54s)
creating index...
index created!
INFO subprocess.py:  53: detection range command 0: tools/test_net.py --range 0 1477 --cfg outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/test/posetrack_v1.0_val/keypoint_rcnn/detection_range_config.yaml NUM_GPUS 1
INFO subprocess.py:  53: detection range command 1: tools/test_net.py --range 1477 2954 --cfg outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/test/posetrack_v1.0_val/keypoint_rcnn/detection_range_config.yaml NUM_GPUS 1
INFO subprocess.py:  53: detection range command 2: tools/test_net.py --range 2954 4430 --cfg outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/test/posetrack_v1.0_val/keypoint_rcnn/detection_range_config.yaml NUM_GPUS 1
INFO subprocess.py:  53: detection range command 3: tools/test_net.py --range 4430 5906 --cfg outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/test/posetrack_v1.0_val/keypoint_rcnn/detection_range_config.yaml NUM_GPUS 1
INFO subprocess.py:  80: # ---------------------------------------------------------------------------- #
INFO subprocess.py:  82: stdout of subprocess 0 with range [1, 1477]
INFO subprocess.py:  83: # ---------------------------------------------------------------------------- #
tools/test_net.py: line 10: Test a Fast R-CNN network on an image database.: command not found
tools/test_net.py: line 12: from: command not found
tools/test_net.py: line 13: from: command not found
tools/test_net.py: line 14: from: command not found
tools/test_net.py: line 15: from: command not found
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
tools/test_net.py: line 18: from: command not found
tools/test_net.py: line 21: from: command not found
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
import: unable to grab mouse `': Resource temporarily unavailable @ error/xwindow.c/XSelectWindow/9047.
tools/test_net.py: line 34: syntax error near unexpected token `FORMAT'
tools/test_net.py: line 34: `FORMAT = '%(levelname)s %(filename)s:%(lineno)4d: %(message)s''
Traceback (most recent call last):
  File "tools/test_net.py", line 142, in <module>
    main(ind_range=args.range, multi_gpu_testing=args.multi_gpu_testing)
  File "tools/test_net.py", line 103, in main
    engine.test_net_on_dataset(multi_gpu=multi_gpu_testing)
  File "/data3/lilin/my_detect_and_track/DetectAndTrack/lib/core/test_engine.py", line 319, in test_net_on_dataset
    num_images, output_dir)
  File "/data3/lilin/my_detect_and_track/DetectAndTrack/lib/core/test_engine.py", line 284, in multi_gpu_test_net_on_dataset
    'detection', num_images, binary, output_dir)
  File "/data3/lilin/my_detect_and_track/DetectAndTrack/lib/utils/subprocess.py", line 67, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/data3/lilin/my_detect_and_track/DetectAndTrack/lib/utils/subprocess.py", line 97, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 2)
```
I've googled a lot but could not find a answer.

**Comment by tlatlbtle** [comment] 2018-07-03 14:29
The same error, need urgent reply.

**Comment by rohitgirdhar** [comment] 2018-07-03 17:01
As mentioned in the error message, the subprocess calls are failing. Have you tried running the command `tools/test_net.py --range 0 1477 --cfg outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/test/posetrack_v1.0_val/keypoint_rcnn/detection_range_config.yaml NUM_GPUS 1` directly on the shell to see what error you get?

Unfortunately this seems to be dependent on specific shell/environment setup, so I can't really reproduce/debug without more information.

**Comment by tlatlbtle** [comment] 2018-07-04 02:43
Error message:
loading annotations into memory...
Done (t=0.45s)
creating index...
index created!
Video-fying the roidb: 100%|##########################################################################################| 5906/5906 [00:03<00:00, 1492.55it/s]
INFO video.py: 200: Video-fied roidb contains 5906 elements
WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
Traceback (most recent call last):
  File "tools/test_net.py", line 150, in <module>
    main(ind_range=args.range, multi_gpu_testing=args.multi_gpu_testing)
  File "tools/test_net.py", line 101, in main
    engine.test_net(ind_range=ind_range)
  File "/home/data/DetectAndTrack-wjb/lib/core/test_engine.py", line 135, in test_net
    model = initialize_model_from_cfg()
  File "/home/data/DetectAndTrack-wjb/lib/core/test_engine.py", line 59, in initialize_model_from_cfg
    init_params=cfg.TEST.INIT_RANDOM_VARS_BEFORE_LOADING)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/model_builder.py", line 61, in create
    return get_func(model_name)(init_model(model_name, train, init_params))
  File "/home/data/DetectAndTrack-wjb/lib/modeling/model_builder.py", line 154, in keypoint_rcnn
    add_roi_keypoint_head_func=get_func(cfg.KRCNN.ROI_KEYPOINTS_HEAD))
  File "/home/data/DetectAndTrack-wjb/lib/modeling/model_builder.py", line 305, in build_generic_fast_rcnn_model
    build_data_parallel_model(model, _single_gpu_build_func)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/model_builder.py", line 951, in build_data_parallel_model
    single_gpu_build_func(model)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/model_builder.py", line 197, in _single_gpu_build_func
    blob_conv, dim_conv, spatial_scale_conv = add_conv_body_func(model)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/FPN3D.py", line 51, in add_fpn_ResNet101_conv5_body
    ResNet.stage_info_ResNet101_conv5)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/FPN3D.py", line 98, in add_fpn_generic_onto_body
    conv_body_func(model)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/ResNet3D.py", line 389, in add_ResNet101_conv5_body
    return add_ResNet_convX_body(model, (3, 4, 23, 3), freeze_at=2)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/ResNet3D.py", line 262, in add_ResNet_convX_body
    p = model.AffineChannelNd(p, 'res_conv1_bn', dim_out=feat_dims[0], inplace=True)
  File "/home/data/DetectAndTrack-wjb/lib/modeling/detector.py", line 107, in AffineChannelNd
    return self.net.AffineChannelNd([blob_in, scale, bias], blob_in)
  File "/usr/local/caffe2_build/caffe2/python/core.py", line 2040, in __getattr__
    ",".join(workspace.C.nearby_opnames(op_type)) + ']'
AttributeError: Method AffineChannelNd is not a registered operator. Did you mean: [AffineChannel]

**Comment by zhujiagang** [comment] 2018-07-04 03:46
@rohitgirdhar  Yes,
`python tools/test_net.py --range 0 1477 --cfg outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/test/posetrack_v1.0_val/keypoint_rcnn/detection_range_config.yaml NUM_GPUS 1`
could work.
@wjbKimberly 
It seems the code could not support multi-gpu setting and we need to comment the lines
https://github.com/facebookresearch/DetectAndTrack/blob/d66734498a4331cd6fde87d8269499b8577a2842/launch.py#L50
https://github.com/facebookresearch/DetectAndTrack/blob/d66734498a4331cd6fde87d8269499b8577a2842/launch.py#L51

**Comment by tlatlbtle** [comment] 2018-07-04 05:05
@zhujiagang  Thanks a lot for your kind help!

**Comment by rohitgirdhar** [comment] 2018-07-04 08:34
The code should work with multi-GPU testing. In @wjbKimberly's case, it seems the additional ops (`AffineChannelNd`) has not been compiled ([instructions](https://github.com/facebookresearch/DetectAndTrack#compile-some-custom-ops)). Closing as it seems the issue is resolved.

**Closed as completed by rohitgirdhar** 2018-07-04 08:34 UTC

**Comment by my-hello-world** [comment] 2018-12-02 12:02
> @rohitgirdhar Yes,
> `python tools/test_net.py --range 0 1477 --cfg outputs/configs/video/2d_best/01_R101_best_hungarian-4GPU.yaml/test/posetrack_v1.0_val/keypoint_rcnn/detection_range_config.yaml NUM_GPUS 1`
> could work.
> @wjbKimberly
> It seems the code could not support multi-gpu setting and we need to comment the lines
> 
> [DetectAndTrack/launch.py](https://github.com/facebookresearch/DetectAndTrack/blob/d66734498a4331cd6fde87d8269499b8577a2842/launch.py#L50)
> 
> Line 50 in [d667344](/facebookresearch/DetectAndTrack/commit/d66734498a4331cd6fde87d8269499b8577a2842)
>  if args.mode in ['train', 'test']: 
> 
> [DetectAndTrack/launch.py](https://github.com/facebookresearch/DetectAndTrack/blob/d66734498a4331cd6fde87d8269499b8577a2842/launch.py#L51)
> 
> Line 51 in [d667344](/facebookresearch/DetectAndTrack/commit/d66734498a4331cd6fde87d8269499b8577a2842)
>  other_opts += '--multi-gpu-testing '

我还是一样的错误哎，有没有其他的建议了啊
